site_name: Superinsight Documentation
site_url: https://docs.superinsight.me/
theme:
  name: material
  logo: assets/images/superinsight/empty.png
  palette:
    primary: custom 
nav:
  - What is Superinsight: index.md
  - Installation: download.md
  - Quickstart: quickstart.md
  - How To Guide:
    - Guide: guide/index.md
    - Manage Case: 
      - Overview: guide/case-contact.md
      - Integration: guide/case-integration.md
    - How to Manage Reports: guide/manage-reports.md
    - Manage Documents: guide/case-folder.md
    - Manage Research: guide/research.md
    - Manage Groups: guide/groups.md
    - Manage Organizations: guide/organizations.md
    - Manage Subscription: guide/subscription.md
    - Support: guide/support.md
  - Credits and Usage: guide/credit-usage.md
  - Release Notes: guide/release-notes.md
  - Login To App: https://app.superinsight.me
  - Official Website: https://www.superinsight.ai
  - Privacy Policy: guide/privacy-policy.md
  - Terms of Use: guide/terms-of-use.md
  - HIPAA Notice: guide/hipaa-notice.md
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - mkdocs-pdf

extra:
  generator: false
  analytics:
    provider: google
    property: G-B69XP516VZ
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/scrollspy.js