site_name: Superinsight Documentation
site_url: https://docs.superinsight.me
theme:
  name: material
  logo: assets/images/superinsight/empty.png
  palette:
    primary: custom 
nav:
  - What is Superinsight: index.md
  - Quickstart: quickstart.md
  - How To Guide:
    - Guide: guide/index.md
    - Manage Contact: guide/case-contact.md
    - Manage Folder: guide/case-folder.md
    - Manage File: guide/case-files.md
    - Manage Report: guide/case-report.md
    - Search: guide/search.md
    - Setting Menu: guide/menu.md
  - Release Notes: guide/release-notes.md
  - Login To App: https://app.superinsight.me
  - Official Website: https://www.superinsight.ai
  - Privacy Policy: guide/privacy-policy.md
  - Terms of Use: guide/terms-of-use.md
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - mkdocs-pdf
  - i18n:
      languages:
        - locale: en
          name: "English"
          build: true
          default: true

extra:
  generator: false
  analytics:
    provider: google
    property: G-B69XP516VZ
extra_css:
  - stylesheets/extra.css